name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/deno-ci.yml@develop
    with:
      deno-version: '1.x'
