name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/deno-ci.yml@v1
    with:
      deno-version: '1.x'
