name: Deploy with APM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - name: Fake deploy
        run: echo 'deploying'
      - name: APM notify
        uses: DiogoRibeiro7/git-actions-collection/.github/actions/apm-integration@main
        with:
          provider: datadog
          api-key: ${{ secrets.DD_API_KEY }}
          environment: demo
