name: Node CI

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: DiogoRibeiro7/git-actions-collection/.github/actions/setup-yarn@develop
      - run: yarn -v
