"""Rust coverage, security and benchmark jobs summarize their results on the run page."""

import json
import os
from pathlib import Path
import shutil

import pytest

from tests.utils.rust_steps import cargo_stub, run_step, runner_temp

FIXTURES = Path("tests/fixtures/rust-security")
posix_only = pytest.mark.skipif(os.name != "posix", reason="Fake runner requires bash (Linux CI)")

# Real `cargo generate-lockfile` output for a crate that depends on smallvec 1.6.0.
CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fixture"
version = "0.1.0"
dependencies = [
 "smallvec",
]

[[package]]
name = "smallvec"
version = "1.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1a55ca5f3b68e41c979bf8c46a6f1da892ca4db8f94023ce0bd32407573b1ac0"
"""

LCOV = """\
SF:{crate}/src/lib.rs
FNF:4
FNH:3
LF:40
LH:30
end_of_record
SF:{crate}/src/full.rs
FNF:1
FNH:1
LF:10
LH:10
end_of_record
"""


def _annotations(stdout: str) -> list[str]:
    return [line for line in stdout.splitlines() if line.startswith("::")]


def _crate(tmp_path: Path) -> Path:
    crate = tmp_path / "crate"
    crate.mkdir()
    return crate


@posix_only
@pytest.mark.parametrize(("minimum", "outcome"), [(80, "success"), (90, "failure")])
def test_coverage_summary_reports_totals_and_least_covered_files(
    tmp_path: Path, minimum: int, outcome: str
) -> None:
    crate = _crate(tmp_path)
    (crate / "lcov.info").write_text(LCOV.format(crate=crate), encoding="utf-8")

    result = run_step(
        "rust-coverage.yml",
        "coverage",
        "Coverage summary",
        crate,
        inputs={"minimum-line-coverage": minimum},
        stubs=cargo_stub(tmp_path / "cargo.log"),
        context={"steps.coverage.outcome": outcome},
    )

    assert result.code == 0, result.stderr
    status = "✅ Passed" if outcome == "success" else "❌ Failed"
    assert result.summary == f"""\
## Rust coverage

| Check | Result |
| --- | --- |
| Coverage | {status}: 80.00% of lines (minimum {minimum}%) |

| Metric | Covered | Total | Coverage |
| --- | ---: | ---: | ---: |
| Lines | 40 | 50 | 80.00% |
| Functions | 4 | 5 | 80.00% |

**Least covered files**

| File | Lines | Coverage |
| --- | ---: | ---: |
| `crate/src/lib.rs` | 30/40 | 75.00% |
"""
    below = ["::error title=Line coverage::Line coverage is 80.00%, below the minimum of 90%."]
    assert _annotations(result.stdout) == (below if minimum == 90 else [])


@posix_only
def test_coverage_summary_without_a_report(tmp_path: Path) -> None:
    crate = _crate(tmp_path)

    result = run_step(
        "rust-coverage.yml",
        "coverage",
        "Coverage summary",
        crate,
        stubs=cargo_stub(tmp_path / "cargo.log"),
        context={"steps.coverage.outcome": "failure"},
    )

    assert result.code == 0, result.stderr
    assert "| Coverage | ❌ Failed: no coverage report |" in result.summary
    assert "| Metric |" not in result.summary


@posix_only
def test_security_summary_lists_audit_and_deny_findings(tmp_path: Path) -> None:
    """The fixtures are real cargo-audit 0.22.2 and cargo-deny 0.20.2 JSON output."""
    crate = _crate(tmp_path)
    (crate / "Cargo.lock").write_text(CARGO_LOCK, encoding="utf-8")
    for name in ("cargo-audit.json", "cargo-deny.jsonl"):
        shutil.copy(FIXTURES / name, runner_temp(crate) / name)

    result = run_step(
        "rust-security.yml",
        "audit",
        "Summary",
        crate,
        inputs={"run-cargo-deny": True},
        context={"steps.audit.outcome": "failure", "steps.deny.outcome": "failure"},
    )

    assert result.code == 0, result.stderr
    assert result.summary == """\
## Rust security

| Check | Result |
| --- | --- |
| cargo-audit | ❌ Failed: 1 vulnerability |
| cargo-deny | ❌ Failed: advisories 1 error, licenses 1 error |

**cargo-audit findings**

| Kind | Advisory | Crate | Title | Fixed in |
| --- | --- | --- | --- | --- |
| vulnerability | [RUSTSEC-2021-0003](https://rustsec.org/advisories/RUSTSEC-2021-0003) \
| `smallvec 1.6.0` | Buffer overflow in SmallVec::insert_many | `>=0.6.14, <1.0.0` or `>=1.6.1` |

**cargo-deny findings**

| Code | Severity | Crate | Finding |
| --- | --- | --- | --- |
| rejected | error | `fixture 0.1.0` \
| failed to satisfy license requirements: rejected: license is not explicitly allowed \
(`GPL-3.0-only`) |
| vulnerability | error | `smallvec 1.6.0` \
| Buffer overflow in SmallVec::insert_many (RUSTSEC-2021-0003) |
"""
    # The audit finding points at the crate's entry in Cargo.lock.
    assert _annotations(result.stdout) == [
        "::error file=crate/Cargo.lock,line=13,title=RUSTSEC-2021-0003 vulnerability"
        "::smallvec 1.6.0: Buffer overflow in SmallVec::insert_many",
        "::error title=cargo-deny rejected::fixture 0.1.0: failed to satisfy license requirements: "
        "rejected: license is not explicitly allowed (`GPL-3.0-only`)",
        "::error title=cargo-deny vulnerability::smallvec 1.6.0: "
        "Buffer overflow in SmallVec::insert_many (RUSTSEC-2021-0003)",
    ]


@posix_only
def test_security_summary_for_a_clean_audit_without_cargo_deny(tmp_path: Path) -> None:
    crate = _crate(tmp_path)
    clean = {"vulnerabilities": {"found": False, "count": 0, "list": []}, "warnings": {}}
    (runner_temp(crate) / "cargo-audit.json").write_text(json.dumps(clean), encoding="utf-8")

    result = run_step(
        "rust-security.yml",
        "audit",
        "Summary",
        crate,
        context={"steps.audit.outcome": "success", "steps.deny.outcome": "skipped"},
    )

    assert result.code == 0, result.stderr
    assert result.summary == """\
## Rust security

| Check | Result |
| --- | --- |
| cargo-audit | ✅ Passed |
| cargo-deny | Not enabled |
"""
    assert _annotations(result.stdout) == []


@posix_only
def test_benchmark_step_marks_its_start(tmp_path: Path) -> None:
    crate = _crate(tmp_path)

    result = run_step(
        "rust-benchmark.yml",
        "benchmark",
        "Run Criterion smoke benchmark",
        crate,
        stubs=cargo_stub(tmp_path / "cargo.log"),
    )

    assert result.code == 0, result.stderr
    assert (runner_temp(crate) / "criterion-start").exists()


def _criterion(crate: Path, name: str, mean: float, low: float, high: float, mtime: int) -> None:
    """Write Criterion 0.7's per-benchmark result files."""
    new = crate / "target" / "criterion" / name / "new"
    new.mkdir(parents=True)
    interval = {"confidence_level": 0.95, "lower_bound": low, "upper_bound": high}
    estimates = {"mean": {"confidence_interval": interval, "point_estimate": mean, "standard_error": 1}}
    benchmark = {"group_id": name, "function_id": None, "value_str": None, "full_id": name}
    for file, data in (("estimates.json", estimates), ("benchmark.json", benchmark)):
        (new / file).write_text(json.dumps(data), encoding="utf-8")
        os.utime(new / file, (mtime, mtime))


@posix_only
def test_benchmark_summary_lists_only_this_runs_benchmarks(tmp_path: Path) -> None:
    """Results restored from the cache predate the start marker and are left out."""
    crate = _crate(tmp_path)
    marker = runner_temp(crate) / "criterion-start"
    marker.touch()
    os.utime(marker, (1000, 1000))
    _criterion(crate, "add_two_numbers", 1500.0, 1400.0, 1650.0, mtime=2000)
    _criterion(crate, "parse", 2_500_000.0, 2_000_000.0, 3_000_000.0, mtime=2000)
    _criterion(crate, "tiny", 850.0, 800.0, 900.0, mtime=2000)
    _criterion(crate, "from_the_cache", 1.0, 1.0, 1.0, mtime=500)

    result = run_step(
        "rust-benchmark.yml",
        "benchmark",
        "Summary",
        crate,
        context={"steps.bench.outcome": "success"},
    )

    assert result.code == 0, result.stderr
    assert result.summary == """\
## Rust benchmarks

| Check | Result |
| --- | --- |
| Criterion | ✅ Passed: 3 benchmarks |

| Benchmark | Mean | 95% confidence interval |
| --- | ---: | ---: |
| `add_two_numbers` | 1.5 µs | 1.4 µs to 1.65 µs |
| `parse` | 2.5 ms | 2 ms to 3 ms |
| `tiny` | 850 ns | 800 ns to 900 ns |

Smoke settings on a shared runner: large changes are signal, small ones are noise.
"""
