name: Release container

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/publish-docker-on-tag.yml@main
    with:
      image: ghcr.io/${{ format('{0}', github.repository) }}
      platforms: linux/amd64,linux/arm64
      target: app
      build-args: |
        APP_MESSAGE=Hello from tag
