name: Canary Release

on:
  push:
    branches: [ develop ]
    tags: [ "*-rc*" ]

jobs:
  release:
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/canary-release.yml@main
    with:
      project-type: python
      build-backend: poetry
      working-directory: .
