name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/python-lint.yml@develop

  test:
    needs: lint
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/coverage-report.yml@develop
