name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/python-lint.yml@main

  test:
    needs: lint
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/coverage-report.yml@main
