name: dependency-review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/dependency-review.yml@develop
