name: Release to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/pypi-publish.yml@v1
    with:
      build-backend: poetry
      environment: pypi
      pre-release: true
