name: Monorepo CI

on:
  push:
  pull_request:

jobs:
  matrix:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/ci-monorepo-matrix.yml@develop
    with:
      groups: '{"pkg-a": ".github/workflows/python-lint.yml","web-app": ".github/workflows/node-ci.yml","infra": ".github/workflows/infra-lint.yml"}'
