name: Canary Release

on:
  push:
    branches: [ main ]
    tags: [ "*-rc*" ]

jobs:
  release:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/canary-release.yml@v1
    with:
      project-type: npm
      working-directory: .
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
