name: Canary Release

on:
  push:
    branches: [ develop ]
    tags: [ "*-rc*" ]

jobs:
  release:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/canary-release.yml@develop
    with:
      project-type: npm
      working-directory: .
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
