name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: DiogoRibeiro7/gh-actions-collection/.github/actions/setup-yarn@main
      - run: yarn lint
      - run: yarn test
