name: lockfile

on:
  pull_request:
    paths:
      - "package.json"
      - "yarn.lock"

jobs:
  check:
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/lockfile-consistency.yml@main
