name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: DiogoRibeiro7/gh-actions-collection/.github/workflows/npm-publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
