version: '3.9'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn django_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SECRET_KEY=changeme
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
