name: Security Scan Example

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write
  id-token: write
  attestations: write

jobs:
  scan:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/security-scan.yml@develop
    with:
      paths: '.'
      skip-trivy: true
      skip-npm-signatures: false
      skip-java-verify: false
      skip-go-verify: false