name: Changelog Auto PR
on:
  workflow_call:
    inputs:
      commit-message:
        required: false
        type: string
        default: 'chore: update changelog'
      branch:
        required: false
        type: string
        default: 'chore/update-changelog'
permissions:
  contents: write
  pull-requests: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Install git-cliff
        run: |
          sudo apt-get update
          sudo apt-get install -y git-cliff
      - name: Generate changelog
        run: git cliff --output CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: ${{ inputs.commit-message }}
          title: ${{ inputs.commit-message }}
          body: 'Update changelog'
          branch: ${{ inputs.branch }}
