name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        description: Go version
        required: false
        type: string
        default: '1.22'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{ inputs.go-version }}
      - name: Run tests
        run: go test ./...
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601
        with:
          version: latest
