name: JS/TS Unit Tests
on:
  pull_request:
    paths:
      - '**/*.ts'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/js-unit-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn test
