name: Kubernetes Manifests Lint
on:
  workflow_call:
    inputs:
      paths:
        description: 'Paths to Kubernetes manifests'
        required: false
        type: string
        default: '.'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz -C /usr/local/bin
      - name: Validate manifests
        run: kubeconform -summary ${{ inputs.paths }}
