name: Permissions Hardened Template

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing with elevated permissions"
