name: Python Type Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/actions/python-type-check/**'
      - '.github/workflows/python-type-check.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  mypy:
    name: Run mypy static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Type check project sources
        uses: ./.github/actions/python-type-check
        with:
          python-version: '3.11'
          working-directory: examples/python-package
          mypy-args: src
