name: Release Container

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: DiogoRibeiro7/git-actions-collection/.github/workflows/publish-docker-on-tag.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      context: .
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64
      target: prod
      build-args: |
        NODE_ENV=production
        API_URL=https://api.example.com
      labels: true
      registry: ghcr.io
    secrets:
      REGISTRY_USERNAME: ${{ secrets.GHCR_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
